# This is a basic workflow to help you get started with Actions


name: CI - Dev

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [development]
  pull_request:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Version Pull Request
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name $GITHUB_ACTOR
          npm_version=$(npm version patch) 
          echo $npm_version
          git push --tags
          git push

      - name: Version Push
        if: github.event_name == 'push'
        run: |
          git config --global user.name $GITHUB_ACTOR
          npm_version=$(npm version patch) 
          echo $npm_version
          git push --tags
          git push origin HEAD:$GITHUB_REF

      - name: Install Dependencies
        run: npm install

      - name: Lint code and Fix Simple Issues
        run: npm run lint-fix

      - name: Build Project
        run: npm run build-prod

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: dist
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/jz-portfolio
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: dist
          path: dist/jz-portfolio
      - name: Deploy To Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting:jlz-portfolio-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEV }}
