name: Workflow Orchestrator v2
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-orchestrator-v2
on:
  pull_request_target:
    branches: ["*", "development", "main"]
    types:
      - opened
      - closed
      - synchronize
permissions: write-all
jobs:
  versionDev:
    if: ${{ github.base_ref != 'main' }}
    uses: ./.github/workflows/version.yml
    secrets: inherit
  deployDev:
    needs: [versionDev]
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
  deployProd:
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
  
