name: Workflow Orchestrator v3
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-orchestrator-v3
on:
  pull_request_target:
    branches: ["*", "development", "main"]
    types:
      - opened
      - closed
      - synchronize
permissions: write-all
jobs:
  versionDev:
    if: ${{ github.base_ref != 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    uses: ./.github/workflows/version.yml
    secrets: inherit
  deployDevPreview:
    if: ${{ github.base_ref != 'main' && github.event.pull_request.head.repo.full_name == github.repository && (github.event.action == 'opened' || github.event.action == 'synchronize') }}
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
  deployDevRelease:
    needs: [versionDev]
    if: ${{ github.base_ref != 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true && needs.versionDev.outputs.versionType == 'stop' }}
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
  deployProd:
    if: ${{ github.base_ref == 'main' }}
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
