name: Workflow Orchestrator v3
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-orchestrator-v3
on:
  pull_request_target:
    branches: ["*", "development", "main"]
    types:
      - opened
      - closed
      - synchronize
permissions: write-all
jobs:
  versionDev:
    if: ${{ github.base_ref != 'main' }}
    uses: ./.github/workflows/version.yml
    secrets: inherit
  deployDev:
    needs: [versionDev]
    if: ${{ needs.versionDev.outputs.versionType == 'stop' }}
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit
  deployProd:
    if: ${{ github.base_ref == 'main' }}
    uses: ./.github/workflows/main-deploy-workflow.yml
    secrets: inherit

