name: Workflow Orchestrator
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-orchestrator
  cancel-in-progress: true
on:
  pull_request_target:
    types:
      - closed
      - synchronize
jobs:
  analyze-code:
    uses: ./.github/workflows/codeql-analysis2.yml
  version:
    needs: ["analyze-code"]
    if: ${{github.event.action == 'closed' }}
    uses: ./.github/workflows/version-on-merge.yml
    secrets: inherit
  deploy-dev-pr-preview:
    needs: ["analyze-code", "version"]
    if: ${{ github.event.action == 'synchronize'  && github.base_ref == 'development' }}
    uses: ./.github/workflows/firebase-hosting-pull-request-development.yml
    secrets: inherit
  deploy-prod-pr-preview:
    needs: ["analyze-code", "version"]
    if: ${{ github.event.action == 'synchronize' && github.base_ref == 'main' }}
    uses: ./.github/workflows/firebase-hosting-pull-request.yml
    secrets: inherit
  deploy-dev:
    needs: ["analyze-code", "version"]
    if: ${{ github.event.action == 'closed'  && github.base_ref == 'development'}}
    uses: ./.github/workflows/firebase-hosting-merge-development.yml
    secrets: inherit
  deploy-prod:
    needs: ["analyze-code", "version"]
    if: ${{ github.event.action == 'closed' && github.base_ref == 'main' }}
    uses: ./.github/workflows/firebase-hosting-merge.yml
    secrets: inherit
  check-deploy-job:
    runs-on: ubuntu-latest
    needs:
      [
        "analyze-code",
        "version",
        "deploy-dev-pr-preview",
        "deploy-prod-pr-preview",
        "deploy-dev",
        "deploy-prod",
      ]
    if: ${{ always() }}
    steps:
      - run: |
          if [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'failure' && '${{ needs.deploy-prod-pr-preview.result }}' == 'failure' && '${{ needs.deploy-dev.result }}' == 'failure' && '${{ needs.deploy-prod.result }}' == 'failure' ]]; then
             echo "Deploy Failed"
             exit 1
          elif [[ '${{ needs.deploy-dev-pr-preview.result }}' == 'success' || '${{ needs.deploy-prod-pr-preview.result }}' == 'success' || '${{ needs.deploy-dev.result }}' == 'success' || '${{ needs.deploy-prod.result }}' == 'success' ]]; then
             exit 0
          else
            exit 1
          fi

