name: Workflow Orchestrator v2
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-orchestrator-v2
  cancel-in-progress: true
on:
  pull_request_target:
    branches: ["*", "development", "main"]
    types:
      - opened
      - closed
      - synchronize
permissions: write-all
jobs:
  version:
    uses: ./.github/workflows/version/version.yml
    secrets: inherit
  # deploy:
  #   uses: ./.github/workflows/deploy/main-deploy-workflow.yml
  #   secrets: inherit