name: Version On Merge
'on':
  push:
    branches: ['*']
env:
  commitMsg: $ {{ github.event.commits[0].message}}
jobs:
  version-patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: 
          version: 18
          cache: 'npm'
      - name: version
        if: startsWith(fromJSON(env.patchCommitTypes), env.commitMsg)
        run: 'echo $commitMsg && echo $patchCommitTypes && npm i && npm version'
    env:
      patchCommitTypes: '[ "fix","perf","revert","docs","style","chore","refactor","test","build","ci"]'
  
    
          
        
  
