name: Version On Merge
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-versioning
"on":
  push:
    branches: ["development"]
permissions: write-all
env:
  commitMsg: ${{ github.event.commits[0].message }}
jobs:
  version-patch:
    strategy:
      matrix:
        types: [ "fix(", "perf(", "revert(", "docs(", "style(", "chore(", "refactor(","test(","build(","ci(",]
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        if: contains(env.commitMsg, matrix.types)
        uses: actions/checkout@v3
      - name: Use Node.js 18
        if: contains(env.commitMsg, matrix.types)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: pull tags
        if: contains(env.commitMsg,  matrix.types)
        run: git pull --tags
      - name: set email
        if: contains(env.commitMsg,  matrix.types)
        run: git config --local user.email '10226084+Zwiqler94@users.noreply.github.com'
      - name: set username
        if: contains(env.commitMsg,  matrix.types)
        run: git config --local user.name 'Zwiqler94'
      - name: npm install
        if: contains(env.commitMsg,  matrix.types)
        run: npm ci
      - name: version
        if: contains(env.commitMsg,  matrix.types)
        run: npm version patch
      - name: push tags
        if: contains(env.commitMsg,  matrix.types)
        run: git push --tags
      - name: push code
        if: contains(env.commitMsg,  matrix.types)
        run: git push
  version-minor:
    needs: version-patch
    strategy:
      matrix:
        types: ["feat"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: contains(env.commitMsg, matrix.types)
        uses: actions/checkout@v3
      - name: Use Node.js 18
        if: contains(env.commitMsg, matrix.types)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: version
        if: contains(env.commitMsg,  matrix.types)
        run: |
          git pull --tags
          git config --local user.name 'Zwiqler94'
          git config --local user.email '10226084+Zwiqler94@users.noreply.github.com'
          npm ci
          npm version minor
          git push --tags
          git push

  version-major:
    needs: [version-minor, version-patch]
    strategy:
      matrix:
        types: ["BREAKING CHANGE", "!:"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: contains(env.commitMsg, matrix.types)
        uses: actions/checkout@v3
      - name: Use Node.js 18
        if: contains(env.commitMsg, matrix.types)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: version
        if: contains(env.commitMsg,  matrix.types)
        run: |
          git pull --tags
          git config --local user.name 'Zwiqler94'
          git config --local user.email '10226084+Zwiqler94@users.noreply.github.com'
          npm ci
          npm version major
          git push --tags
          git push
