name: Version On Merge
'on':
  push:
    branches: ['*']
jobs:
  version-patch:
    if: startsWith(fromJSON($patchCommitTypes), $commitMsg)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: 
          version: 18
          cache: 'npm'
      - run: npm i
    env:
      commitMsg: $ {{ github.event.commits.message}}
      patchCommitTypes: '[ "fix","perf","revert","docs","style","chore","refactor","test","build","ci"]'
  version-minor:
    if: ${{ startsWith(fromJSON(env.minorCommitTypes), env.commitMsg) }}) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: 
          version: 18
          cache: 'npm'
      - run: npm i
    env:
      commitMsg: $ {{ github.event.commits.message}}
      minorCommitTypes: "['feat']"
  version-major:
    if: contains(fromJSON($env.majorCommitTypes), $env.commitMsg)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with: 
          version: 18
          cache: 'npm'
      - run: npm i
    env:
      commitMsg: $ {{ github.event.commits.message}}
      majorCommitTypes: '[ "!", "BREAKING"]'
  
    
          
        
  
