name: Version On Merge
'on':
  push:
    branches: ['*']
env:
  commitMsg: ${{ github.event.commits[0].message }}
jobs:
  version-patch:
    strategy:
      matrix: 
       types: ["fix(","perf(","revert(","docs(","style(","chore(","refactor(","test(","build(","ci("]
    runs-on: ubuntu-latest
    steps:
      - name: check 1
        run: 'echo ${{ matrix.types }} && echo $commitMsg'
      - name: checkout
        if: contains(env.commitMsg, ${{ matrix.types }})
        uses: actions/checkout@v3
      - name: Use Node.js 18
        if: contains(env.commitMsg, ${{ matrix.types }})
        uses: actions/setup-node@v3
        with: 
          version: 18
          cache: 'npm'
      - name: version
        if: contains(env.commitMsg, ${{ matrix.types }})
        run: 'npm i && npm version patch'
    
          
        
  
