name: Version Test
'on':
  - push
env:
  GH_TOKEN: '${{ secrets.GH_TOKEN }}'
  commitMsg: '${{ github.event.commits[0].message }}'
jobs:
  VERIFY:
    runs-on: ubuntu-latest
    outputs:
      versionType: ${{ steps.verifyCommit.outputs.versionType }}
    steps:
      - name: check commit
        id: verifyCommit
        run: |
            if [[ $commitMsg =~ (BREAKING CHANGE|^(.|\s)+(\(.|\s\))?!:(.|\s)+$) ]]; then
                echo "version-type=major" >> "$GITHUB_OUTPUT"
                echo "version-type=major" 
                exit 0
            elif [[ $commitMsg =~ ^feat(\(.+\))?:(.|\s)+$ ]]; then
                echo "version-type=minor" >> "$GITHUB_OUTPUT"
                echo "version-type=minor"
                exit 0
            elif [[ $commitMsg =~ ^(fix(\(.+\))?|perf(\(.+\))?|revert(\(.+\))?|docs(\(.+\))?|style(\(.+\))?|chore(\(.+\))?|refactor(\(.+\))?|test(\(.+\))?|build(\(.+\))?|ci(\(.+\))?):(.|\s)+$ ]]; then
                echo "version-type=patch" >> "$GITHUB_OUTPUT"
                echo "version-type=patch"
                exit 0
            else
                echo "Can't determine version from commit!!!"
                exit 1
            fi
  VERSION:
    runs-on: ubuntu-latest
    needs: VERIFY
    env:
      A: ${{ needs.VERIFY.outputs.versionType }}
    steps:
        - run: echo "$A"
  

